### ISSUE TITLE
[Bug] Generation failure of pbf shards in RUS

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-generator#189]
I get a generation failure in RUS locally on my system with the following sharded pbf files.

```
21/08/12 16:06:08 ERROR Executor: Exception in task 682.3 in stage 4.0 (TID 8766)
org.openstreetmap.atlas.exception.CoreException: Error during task Way Sectioned Atlas Creation for shard RUS_10-615-346 :
	at org.openstreetmap.atlas.generator.AtlasGeneratorHelper.lambda$sectionAtlas$2f38d685$1(AtlasGeneratorHelper.java:431)
	at org.apache.spark.api.java.JavaPairRDD$.$anonfun$pairFunToScalaFun$1(JavaPairRDD.scala:1044)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1371)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1298)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1362)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1186)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:360)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:311)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openstreetmap.atlas.exception.CoreException: Couldn't find node at POINT (36.9266202 50.5129055) while sectioning Line [Line: id=362729841000000, polyLine=LINESTRING (36.9266202 50.5129055, 36.9259448 50.5128815, 36.9234523 50.512998, 36.9055813 50.5135254, 36.9048755 50.5135274), [Tags: [last_edit_user_name => Vorrutyer_bak], [last_edit_changeset => 32926830], [last_edit_time => 1438076138000], [last_edit_user_id => 622109], [iso_country_code => RUS], [highway => track], [last_edit_version => 1]]] for Atlas 10-615-346
	at org.openstreetmap.atlas.geography.atlas.raw.sectioning.AtlasSectionProcessor.createNode(AtlasSectionProcessor.java:397)
	at org.openstreetmap.atlas.geography.atlas.raw.sectioning.AtlasSectionProcessor.createEdge(AtlasSectionProcessor.java:329)
	at org.openstreetmap.atlas.geography.atlas.raw.sectioning.AtlasSectionProcessor.createSections(AtlasSectionProcessor.java:454)
	at org.openstreetmap.atlas.geography.atlas.raw.sectioning.AtlasSectionProcessor.section(AtlasSectionProcessor.java:663)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.openstreetmap.atlas.geography.atlas.raw.sectioning.AtlasSectionProcessor.run(AtlasSectionProcessor.java:186)
	at org.openstreetmap.atlas.generator.AtlasGeneratorHelper.lambda$sectionAtlas$2f38d685$1(AtlasGeneratorHelper.java:426)
	... 18 more
```

<img width="149" alt="Screen Shot 2021-08-17 at 9 52 30 AM" src="https://user-images.githubusercontent.com/5851115/129738182-fb6b4b8b-5413-4aae-9e1d-4b64adfc2ac9.png">
And this sharding file:
[sharding.txt](https://github.com/osmlab/atlas-generator/files/7000461/sharding.txt)

after coping the sharding txt file and pbf files to the correct folder, I just changed the countries in the gradle.properties file to RUS
`generator.local.countries=RUS`
and then ran ` ./gradlew run`

I wasn't able to reproduce it if I only including the shard that was showing the issue. By including the shards around that shard I was able to reproduce it.

As a note:
It looks like way 362729841 crosses over the corner of 10-616-345 but has no nodes in that shard. Shard 10-616-345 is kitty-corner to the shard that sees the issue (10-615-346). This way is not part of any relation and is not close to a boundary so I'm not sure that the PR that is outstanding will address this issue. My guess is that there is a boundary case somewhere when scanning for ways in a neighboring shard. Maybe if a way crosses a surrounding shard but has no nodes in any surrounding shard then things break?

**Comment by atiannicelli** [comment]
This has been solved by https://github.com/osmlab/atlas-generator/pull/188
